# Generated by Django 5.0.2 on 2024-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='description',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
