# Generated by Django 5.0.2 on 2024-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date_added',
        ),
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
